export const objStudents = [
    {
      "nombre": "Juan",
      "apellido": "Pérez",
      "numeroDocumento": "1234567890",
      "diagnosticoMental": "Autismo",
      "edad": 10,
      "datos": true,
      "calificado": false,
      "nombrePadre": "Carlos Pérez",
      "nombreMadre": "María López",
      "telefono": "3101234567"
    },
    {
      "nombre": "Briand",
      "apellido": "Marín",
      "numeroDocumento": "1126588201",
      "diagnosticoMental": "Esquizofrenia",
      "edad": 18,
      "datos": true,
      "calificado": false,
      "nombrePadre": "Indefinido",
      "nombreMadre": "Graciela Hernandéz",
      "telefono": "3235287523"
    },
    {
      "nombre": "María",
      "apellido": "García",
      "numeroDocumento": "2345678901",
      "diagnosticoMental": "Síndrome de Down",
      "edad": 12,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Luis García",
      "nombreMadre": "Ana Ramírez",
      "telefono": "3201234567"
    },
    {
      "nombre": "Pedro",
      "apellido": "Rodríguez",
      "numeroDocumento": "3456789012",
      "diagnosticoMental": "(TDAH)",
      "edad": 11,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Jorge Rodríguez",
      "nombreMadre": "Laura Martínez",
      "telefono": "3001234567"
    },
    {
      "nombre": "Sofía",
      "apellido": "Martínez",
      "numeroDocumento": "4567890123",
      "diagnosticoMental": "Discapacidad Intelectual",
      "edad": 9,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Andrés Martínez",
      "nombreMadre": "Carmen Gómez",
      "telefono": "3111234567"
    },
    {
      "nombre": "Carlos",
      "apellido": "López",
      "numeroDocumento": "5678901234",
      "diagnosticoMental": "Autista",
      "edad": 13,
      "datos": false,
      "calificado": true,
      "nombrePadre": "Miguel López",
      "nombreMadre": "Lucía Sánchez",
      "telefono": "3121234567"
    },
    {
      "nombre": "Ana",
      "apellido": "Ramírez",
      "numeroDocumento": "6789012345",
      "diagnosticoMental": "Trastorno del Lenguaje",
      "edad": 8,
      "datos": true,
      "calificado": false,
      "nombrePadre": "Ricardo Ramírez",
      "nombreMadre": "Patricia Torres",
      "telefono": "3131234567"
    },
    {
      "nombre": "David",
      "apellido": "Gómez",
      "numeroDocumento": "7890123456",
      "diagnosticoMental": "Dislexia",
      "edad": 10,
      "datos": false,
      "calificado": true,
      "nombrePadre": "Juan Gómez",
      "nombreMadre": "Marta Fernández",
      "telefono": "3141234567"
    },
    {
      "nombre": "Laura",
      "apellido": "Fernández",
      "numeroDocumento": "8901234567",
      "diagnosticoMental": "Síndrome de Asperger",
      "edad": 12,
      "datos": true,
      "calificado": false,
      "nombrePadre": "Pablo Fernández",
      "nombreMadre": "Sonia Pérez",
      "telefono": "3151234567"
    },
    {
      "nombre": "Jorge",
      "apellido": "Sánchez",
      "numeroDocumento": "9012345678",
      "diagnosticoMental": "Trastorno del Desarrollo Intelectual",
      "edad": 9,
      "datos": false,
      "calificado": true,
      "nombrePadre": "Eduardo Sánchez",
      "nombreMadre": "Elena García",
      "telefono": "3161234567"
    },
    {
      "nombre": "Sara",
      "apellido": "Díaz",
      "numeroDocumento": "0123456789",
      "diagnosticoMental": "Trastorno del Espectro Autista",
      "edad": 11,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Mario Díaz",
      "nombreMadre": "Beatriz Gómez",
      "telefono": "3171234567"
    },
    {
      "nombre": "Daniel",
      "apellido": "Mendoza",
      "numeroDocumento": "1122334455",
      "diagnosticoMental": "(TDAH)",
      "edad": 8,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Alberto Mendoza",
      "nombreMadre": "Claudia Ramírez",
      "telefono": "3181234567"
    },
    {
      "nombre": "Paula",
      "apellido": "Castro",
      "numeroDocumento": "2233445566",
      "diagnosticoMental": "Síndrome de Down",
      "edad": 13,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Felipe Castro",
      "nombreMadre": "Mariana Torres",
      "telefono": "3191234567"
    },
    {
      "nombre": "Luis",
      "apellido": "Vargas",
      "numeroDocumento": "3344556677",
      "diagnosticoMental": "Trastorno del Lenguaje",
      "edad": 9,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Héctor Vargas",
      "nombreMadre": "Lorena Pérez",
      "telefono": "3201234567"
    },
    {
      "nombre": "Valentina",
      "apellido": "Ortega",
      "numeroDocumento": "4455667788",
      "diagnosticoMental": "Autismo",
      "edad": 11,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Gustavo Ortega",
      "nombreMadre": "Natalia López",
      "telefono": "3211234567"
    },
    {
      "nombre": "Miguel",
      "apellido": "Núñez",
      "numeroDocumento": "5566778899",
      "diagnosticoMental": "Discapacidad Intelectual",
      "edad": 12,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Ramón Núñez",
      "nombreMadre": "Rosa Ramírez",
      "telefono": "3221234567"
    },
    {
      "nombre": "Camila",
      "apellido": "Ruiz",
      "numeroDocumento": "6677889900",
      "diagnosticoMental": "Síndrome de Asperger",
      "edad": 10,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Alejandro Ruiz",
      "nombreMadre": "Adriana Fernández",
      "telefono": "3231234567"
    },
    {
      "nombre": "Alejandro",
      "apellido": "Peña",
      "numeroDocumento": "7788990011",
      "diagnosticoMental": "Dislexia",
      "edad": 8,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Sergio Peña",
      "nombreMadre": "Verónica Gómez",
      "telefono": "3241234567"
    },
    {
      "nombre": "Lucía",
      "apellido": "Moreno",
      "numeroDocumento": "8899001122",
      "diagnosticoMental": "Trastorno del Desarrollo Intelectual",
      "edad": 13,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Nicolás Moreno",
      "nombreMadre": "Gabriela Torres",
      "telefono": "3251234567"
    },
    {
      "nombre": "Fernando",
      "apellido": "Rojas",
      "numeroDocumento": "9900112233",
      "diagnosticoMental": "(TDAH)",
      "edad": 9,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Diego Rojas",
      "nombreMadre": "Tatiana Ramírez",
      "telefono": "3261234567"
    },
    {
      "nombre": "Isabella",
      "apellido": "Navarro",
      "numeroDocumento": "0011223344",
      "diagnosticoMental": "Trastorno del Espectro Autista",
      "edad": 12,
      "datos": true,
      "calificado": true,
      "nombrePadre": "Hernán Navarro",
      "nombreMadre": "Andrea López",
      "telefono": "3271234567"
    },
    {
      "nombre": "Tomás",
      "apellido": "Silva",
      "numeroDocumento": "1122334456",
      "diagnosticoMental": "Síndrome de Down",
      "edad": 10,
      "datos": false,
      "calificado": false,
      "nombrePadre": "Iván Silva",
      "nombreMadre": "Viviana Torres",
      "telefono": "3281234567"
    }
  ]