# Generated by Django 5.0.7 on 2024-07-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idsexo', models.AutoField(db_column='idSexo', primary_key=True, serialize=False)),
                ('sexo', models.TextField()),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
    ]
