# Generated by Django 5.0.7 on 2024-08-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.DeleteModel(
            name='Areaslogros',
        ),
        migrations.DeleteModel(
            name='Datosmedicos',
        ),
        migrations.DeleteModel(
            name='Eps',
        ),
        migrations.DeleteModel(
            name='Historiaclinica',
        ),
        migrations.DeleteModel(
            name='Informe',
        ),
        migrations.DeleteModel(
            name='Logros',
        ),
        migrations.DeleteModel(
            name='Personas',
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
        migrations.DeleteModel(
            name='Rh',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
        migrations.DeleteModel(
            name='Tipodocumento',
        ),
        migrations.DeleteModel(
            name='Tipoparentesco',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
